// General
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTH_TOGGLE_LOADING = 'AUTH_TOGGLE_LOADING'

// User data
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const UPDATE_USERNAME_ERROR = 'UPDATE_USERNAME_ERROR'
export const CLEAR_USER_MSG = 'CLEAR_USER_MSG'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

// Passwords & verifications
export const VERIFY_PASSWORD_OTP = 'VERIFY_PASSWORD_OTP'
export const VERIFY_PASSWORD_OTP_FAIL = 'VERIFY_PASSWORD_OTP_FAIL'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL'
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL'
export const RESEND_OTP_CODE = 'RESEND_OTP_CODE'
export const RESEND_OTP_CODE_FAIL = 'RESEND_OTP_CODE_FAIL'

// Profile
export const GET_PROVINCES = 'GET_PROVINCES'
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES'
export const GET_ALL_PROFILES_ERROR = 'GET_ALL_PROFILES_ERROR'
export const ADD_PROFILE_IMAGES = 'ADD_PROFILE_IMAGES'
export const GET_PROFILE_IMAGES = 'GET_PROFILE_IMAGES'
export const GET_PROFILE_IMAGES_ERROR = 'GET_PROFILE_IMAGES_ERROR'
export const DELETE_PROFILE_IMAGES = 'DELETE_PROFILE_IMAGES'
export const DELETE_PROFILE_IMAGES_ERROR = 'DELETE_PROFILE_IMAGES_ERROR'
export const RENEW_MEMBERSHIP = 'RENEW_MEMBERSHIP'
export const RENEW_MEMBERSHIP_ERROR = 'RENEW_MEMBERSHIP_ERROR'
export const CLEAR_PROFILE_ALERTS = 'CLEAR_PROFILE_ALERTS'


// Transactions
export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS'
export const GET_USER_TRANSACTIONS_ERROR = 'GET_USER_TRANSACTIONS_ERROR'
export const CREATE_WITHDRAWAL_ORDER = 'CREATE_WITHDRAWAL_ORDER'
export const CREATE_WITHDRAWAL_ORDER_ERROR = 'CREATE_WITHDRAWAL_ORDER_ERROR'
export const GET_TRANSACTION_BY_ID = 'GET_TRANSACTION_BY_ID'
export const GET_TRANSACTION_BY_ID_ERROR = 'GET_TRANSACTION_BY_ID_ERROR'
export const TOGGLE_LOADING_TRANSACTIONS = 'TOGGLE_LOADING_TRANSACTIONS'
export const GET_PICKUP_POINTS = 'GET_PICKUP_POINTS'
export const GET_PICKUP_POINTS_ERROR = 'GET_PICKUP_POINTS_ERROR'
export const SEND_MONEY_TO_FRIENDS = 'SEND_MONEY_TO_FRIENDS'
export const SEND_MONEY_TO_FRIENDS_ERROR = 'SEND_MONEY_TO_FRIENDS_ERROR'

// Support:
export const SEND_SUPPORT_TICKET = 'SEND_SUPPORT_TICKET'
export const SEND_SUPPORT_TICKET_ERROR = 'SEND_SUPPORT_TICKET_ERROR'
export const SUPPORT_TOGGLE_LOADING = 'SUPPORT_TOGGLE_LOADING'